[project]
authors = [
    {name = "FapC_VS", email = "ian.herzogpohl@gmail.com"}
]
description = "test"
name = "FapC_VS"
version = "0.0.0"
readme = "README.md"
requires-python = ">=3.7"

# TODO: Keep this here until pixi releases building capabilities
dependencies = [
    "loguru>=0.7.2,<0.8",
]

[build-system]
requires = ["setuptools"]

[tool.setuptools.packages.find]
where = ["."]
include = ["*"]
